openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: task
paths:
  /task:
    post:
      operationId: createtask
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
          description: successful operation
      summary: Creates the data
      tags:
      - task
      x-eov-operation-handler: controllers/TaskController
  /task/{taskId}:
    delete:
      operationId: deletetask
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: taskId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - task
      x-eov-operation-handler: controllers/TaskController
    get:
      operationId: gettask
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: taskId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
          description: successful operation
      summary: Get the element
      tags:
      - task
      x-eov-operation-handler: controllers/TaskController
    put:
      operationId: updatetask
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: taskId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/task'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task'
          description: successful operation
      summary: Updates the element
      tags:
      - task
      x-eov-operation-handler: controllers/TaskController
  /task/getAll:
    get:
      operationId: getAlltask
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/task'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - task
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/TaskController
  /task/getByParams:
    get:
      operationId: getByParamstask
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/task'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - task
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/TaskController
components:
  schemas:
    task:
      example:
        tpriority: tpriority
        ttype: ttype
        tname: tname
        _id: _id
        tperson: tperson
      properties:
        _id:
          type: string
        tname:
          type: string
        ttype:
          type: string
        tperson:
          type: string
        tpriority:
          type: string
      required:
      - tname
      - tperson
      - tpriority
      - ttype
      type: object
